5.2b: API examples

In [1]:
from randomuser import RandomUser
import pandas as pd

In [2]:
randomUser = RandomUser()

In [3]:
userList = randomUser.generate_users(10)
userList

[<randomuser.RandomUser at 0x134f9a94950>,
 <randomuser.RandomUser at 0x134f9a94980>,
 <randomuser.RandomUser at 0x134f9a949b0>,
 <randomuser.RandomUser at 0x134f9a949e0>,
 <randomuser.RandomUser at 0x134f9a94a10>,
 <randomuser.RandomUser at 0x134f9a94a40>,
 <randomuser.RandomUser at 0x134f9a94a70>,
 <randomuser.RandomUser at 0x134f9a94aa0>,
 <randomuser.RandomUser at 0x134f9a94ad0>,
 <randomuser.RandomUser at 0x134f9a94b00>]

In [11]:
for thisUser in userList:
    print(thisUser.get_full_name() + ", " + thisUser.get_email())

Nikodem Dreyer, nikodem.dreyer@example.com
Steven Korsvik, steven.korsvik@example.com
Liesbeth Van Wersch, liesbeth.vanwersch@example.com
Clémence Aubert, clemence.aubert@example.com
Poliana da Cunha, poliana.dacunha@example.com
Efe Egeli, efe.egeli@example.com
Magnus Jensen, magnus.jensen@example.com
Teresa West, teresa.west@example.com
Buse Karabulut, buse.karabulut@example.com
Abir Broekema, abir.broekema@example.com

In [15]:
for thisUser in userList:
    print(thisUser.get_picture())

https://randomuser.me/api/portraits/men/88.jpg
https://randomuser.me/api/portraits/men/44.jpg
https://randomuser.me/api/portraits/women/23.jpg
https://randomuser.me/api/portraits/women/59.jpg
https://randomuser.me/api/portraits/women/82.jpg
https://randomuser.me/api/portraits/men/94.jpg
https://randomuser.me/api/portraits/men/51.jpg
https://randomuser.me/api/portraits/women/2.jpg
https://randomuser.me/api/portraits/women/9.jpg
https://randomuser.me/api/portraits/women/81.jpg

In [18]:
def getUsers():
    userData = []
    for thisUser in RandomUser.generate_users(10):
        userData.append({"Name": thisUser.get_full_name(),
                        "Gender": thisUser.get_gender(),
                        "City": thisUser.get_city(),
                        "State": thisUser.get_state(),
                        "Email": thisUser.get_email(),
                        "DOB": thisUser.get_dob(),
                        "Picture": thisUser.get_picture()})
    return userData
df1 = pd.DataFrame(getUsers())
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Norman Metzger,male,Friedrichroda,Hessen,norman.metzger@example.com,1956-05-01T23:38:28.277Z,https://randomuser.me/api/portraits/men/90.jpg
1,Stella Martin,female,Warrnambool,New South Wales,stella.martin@example.com,1962-02-08T15:06:49.176Z,https://randomuser.me/api/portraits/women/56.jpg
2,Isabella Johansen,female,Kongsvinger,Hovedstaden,isabella.johansen@example.com,1952-05-27T23:53:32.360Z,https://randomuser.me/api/portraits/women/30.jpg
3,Berfin Munneke,female,Jabeek,Limburg,berfin.munneke@example.com,1965-04-29T11:13:29.230Z,https://randomuser.me/api/portraits/women/52.jpg
4,Tomas Aadland,male,Kvam,Telemark,tomas.aadland@example.com,1982-10-14T21:22:43.610Z,https://randomuser.me/api/portraits/men/89.jpg
5,Greg Reyes,male,Tulsa,West Virginia,greg.reyes@example.com,1948-06-11T07:46:40.091Z,https://randomuser.me/api/portraits/men/64.jpg
6,علی رضا کوتی,male,اردبیل,اردبیل,aalyrd.khwty@example.com,1990-01-03T17:05:47.250Z,https://randomuser.me/api/portraits/men/49.jpg
7,Samira Grue,female,Sand,Nord-Trøndelag,samira.grue@example.com,1983-05-22T21:19:22.520Z,https://randomuser.me/api/portraits/women/43.jpg
8,Doris Hughes,female,Cairns,Queensland,doris.hughes@example.com,1970-01-19T15:38:00.127Z,https://randomuser.me/api/portraits/women/13.jpg
9,Édina Sales,female,Caucaia,Ceará,edina.sales@example.com,1984-09-06T16:55:27.241Z,https://randomuser.me/api/portraits/women/32.jpg

In [19]:
import requests
import json

In [20]:
fvData = requests.get("https://fruityvice.com/api/fruit/all")

In [21]:
fvRes = json.loads(fvData.text)

In [25]:
df2 = pd.json_normalize(fvRes)
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

In [38]:
cherry = df2.loc[df2["name"] == "Cherry"]
(cherry.iloc[0]["family"], cherry.iloc[0]["genus"])

('Rosaceae', 'Prunus')

In [44]:
banana = df2.loc[df2["name"] == "Banana"]
banana.iloc[0]["nutritions.calories"]

96

In [47]:
jokeData = requests.get("https://official-joke-api.appspot.com/jokes/ten")

In [49]:
jokeRes = json.loads(jokeData.text)

In [68]:
df3 = pd.json_normalize(jokeRes)
df3.drop(columns = ["type", "id"], inplace = True)
df3

,setup,punchline
0,Want to hear a chimney joke?,Got stacks of em! First one's on the house
1,What's the difference between a guitar and a f...,"You can tune a guitar but you can't ""tuna""fish!"
2,Why did the man put his money in the freezer?,He wanted cold hard cash!
3,My older brother always tore the last pages of...,I had to draw my own conclusions.
4,Why do chicken coops only have two doors?,"Because if they had four, they would be chicke..."
5,If you put a million monkeys at a million keyb...,the rest of them will write Perl
6,When does a joke become a dad joke?,When it becomes apparent.
7,I just watched a documentary about beavers.,It was the best dam show I ever saw
8,What do you call corn that joins the army?,Kernel.
9,What did one snowman say to the other snow man?,Do you smell carrot?